CREATE DATABASE IF NOT EXISTS SampleDB;
USE SampleDB;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    age INT
);


LOAD DATA LOCAL INFILE 'data.csv' INTO TABLE Users FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
